#%RAML 1.0
title: 部门
baseUri: /api/cli/{version}
version: v1
mediaType: application/json

/dept/view:
  post:
    description: 根据条件查询当前调用者权限范围内的部门列表
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      ids:
        description: 部门ID列表
        type: string[]
        required: true
      name:
        description: 部门名称
        type: string
        required: false
      showName:
        description: 用于显示的部门名称
        type: string
        required: false
      pageNo:
        description: 分页起始页码
        required: false
        default: 1
      pageSize:
        description: 单个分页记录数
        required: false
        default: 10

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "pageNo": 1,
                  "pageSize": 10,
                  "totalRows": 1000,
                  "totalPages": 100,
                  "rows":
                  [
                    {
                      "id": "xxxx",
                      "name": "dev",
                      "showName": "开发部"
                    }
                  ]
                }
              }


/dept/view/{deptID}:
  post:
    description: 根据部门ID查询当前调用者权限范围内的部门信息
    headers:
      Authorization:
        required: true
        type: string

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "id": "xxxx",
                  "name": "dev",
                  "showName": "开发部"
                }
              }


/dept/add:
  post:
    description: 批量新增部门
    headers:
      Authorization:
        required: true
        type: string



/dept/del:
  post:
    description: 批量删除部门
    headers:
      Authorization:
        required: true
        type: string



/dept/mod:
  post:
    description: 修改部门
    headers:
      Authorization:
        required: true
        type: string
