#%RAML 1.0
title: 执行类API
baseUri: /api/cli/{version}
version: v1
mediaType: application/json

types:
  UserNode:
    type: object
    properties:
      UserName:
        description: 执行命令的用户
        type: string
        required: true
      NodeName:
        description: 主机名称
        type: string
        required: true

/node/exec:
  description: 在某个主机上执行命令
  post:
    headers:
      access-token:
        description: token信息
        type: string
        required: true
    queryParameters:
      UserNodes:
        type: UserNode[]
        required: true
      Cmd:
        description: 命令内容
        type: string
        required: true
      PluginType:
        description: 执行命令的插件(MCO or SSH)
        type: string
        required: true
      Timeout:
        description: 命令执行超时时间
        type: uint
        required: true
        
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "Status": "",
                "Message": "",
                "Content": {
                  "TaskIDs": []
                }
              }

/task/view:
  description: 获取某个task的结果
  post:
    headers:
      access-token:
        description: token信息
        type: string
        required: true
    queryParameters:
      TaskIDs:
        type: array
        required: true

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "Status": "",
                "Message": "",
                "Content": {
                  "TaskResults": [{
                    "TaskID": "",
                    "NodeName": "",
                    "UserName": "",
                    "Stdout": "",
                    "Stderr": "",
                    "Status": "",
                    "ExitCode": ""
                  }]
                }
              }
