#%RAML 1.0
title: 黑白名单管理类API
baseUri: /api/cli/{version}
version: v1
mediaType: application/json

/whiteCmd/view:
  description: 白名单列表
  get:
    headers:
      access-token:
        description: token信息
        type: string
        required: true
    queryParameters:
      ids:
        description: 白名单命令的id
        type: array
        required: true

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "",
                "message": "",
                "content": {
                  "whiteCmds": []
                }
              }

/blackCmd/view:
  description: 黑名单列表
  get:
    headers:
      access-token:
        description: token信息
        type: string
        required: true
    queryParameters:
      ids:
        description: 黑名单命令的id
        type: array
        required: true

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "",
                "message": "",
                "content": {
                  "blackCmds": []
                }
              }
