#%RAML 1.0
title: 插件SSH类API
baseUri: /api/cli/{version}/plugin
version: v1
mediaType: application/json

/ssh/view:
  post:
    description: 获取ssh相关信息
    headers:
      access-token:
        description: token信息
        type: string
        required: true
    queryParameters:
      ids:
        description: ssh 信息的id
        type: array
        required: true
      unitIds:
        description: 部署单元id
        type: array
        required: false
      nodeIds:
        description: 主机 id
        type: array
        required: false

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "",
                "message": "",
                "content": {
                  "sshKey": "base64格式",
                  "userName": "ssh登录用户名",
                  "password": "ssh登录密码"
                }
              }
