#%RAML 1.0
title: 插件mco类API
baseUri: /api/cli/{version}/plugin
version: v1
mediaType: application/json

/mco/view:
  get:
    description: 获取mco相关信息
    headers:
      access-token:
        description: token信息
        type: string
        required: true
    queryParameters:
      ids:
        description: mco 信息 id
        type: array
        required: true
      dcIds:
        description: 数据中心id
        type: array
        required: false

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "",
                "message": "",
                "content": {
                  "dcId": "数据中心ID",
                  "dcName": "数据中心名称",
                  "stompAddres": [],
                  "nodesQueue": "待执行命令的主机队列",
                  "replyQueue": "命令执行结果队列",
                  "certFile": "证书文件 base64格式",
                  "keyFile": "key文件 base64格式",
                  "caFile": "ca文件 base64格式",
                  "userName": "MQ 用户的名称",
                  "password": "MQ 用户的密码",
                  "host": "MQ 主机",
                  "signerKeyFile": "签名文件",
                  "signerKeyPassword": "签名的密码",
                  "master": "puppet master ip"
                }
              }
