#%RAML 1.0
title: 用户信息管理
baseUri: /api/cli/{version}
version: v1
mediaType: application/json

types:
  User4Add:
    description: 新增用户模型定义
    type: object
    properties:
      name:
        description: 用户名
        type: string
        required: true
      showName:
        description: 用于显示的用户名
        type: string
        required: false
      pwd:
        description: 用户登录密码
        type: string
        required: true
      email:
        description: 用户邮箱
        type: string
        required: true
      roleID:
        description: 用户所属角色ID
        type: string
        required: true
      deptID:
        description: 用户所属部门ID
        type: string
        required: true
      groupIDs:
        description: 用户所属组ID列表
        type: string[]
        required: false
      stat:
        description: 用户帐号状态
        enum: [enable,disable]
        required: true
        default: enable

/user/add:
  post:
    description: 批量新增用户
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      Users:
        description: 用户信息列表
        type: User4Add[]
        required: true

    responses:
      200:
        body:
          application/json:
            example: |
              {"status": "success", "message": "添加用户成功"}



/user/del:
  post:
    description: 批量删除用户
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      userIDs:
        description: 用户ID列表
        required: true
        type: string[]

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "removed": 3
                }
              }

/user/mod:
  post:
    description: 修改用户信息
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      id:
        description: 用户ID
        required: true
        type: string
      name:
        description: 用户名
        required: false
        type: string
      showName:
        description: 用于显示的用户名
        required: false
        type: string
      pwd:
        description: 用户登录密码
        required: false
        type: string
      email:
        description: 用户邮箱
        required: false
        type: string
      roleID:
        description: 用户所属角色ID
        required: false
        type: string
      deptID:
        description: 用户所属部门ID
        required: false
        type: string
      groupIDs:
        description: 用户所属组ID列表
        required: false
        type: string
        repeat: true
      stat:
        description: 用户帐号状态
        required: false
        enum: [enable,disable]

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "添加用户成功"
              }


/user/view/{userID}:
  post:
    description: 根据用户ID查询用户信息
    headers:
      Authorization:
        required: true
        type: string

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "id": "xxxxxx",
                  "name": "root",
                  "showName": "超级管理员",
                  "email": "root@idcos.com",
                  "stat": "enable",
                  "role":
                  {
                  },
                  "dept":
                  {
                  },
                  "groups":
                  [
                  ]
                }
              }

/user/view:
  post:
    description: 根据条件查询用户列表
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      ids:
        description: 用户ID列表
        type: string[]
        required: true
      name:
        description: 用户名
        required: false
        type: string
      showName:
        description: 用于显示的用户名
        required: false
        type: string
      email:
        description: 用户邮箱
        required: false
        type: string
      stat:
        description: 用户帐号状态
        required: false
        default: "enable"
        enum: [enable,disable]
      pageNo:
        description: 分页起始页码
        required: false
        default: 1
      pageSize:
        description: 单个分页记录数
        required: false
        default: 10

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "pageNo": 1,
                  "pageSize": 10,
                  "totalRows": 1000,
                  "totalPages": 100,
                  "rows":
                  [
                    {
                      "id": "xxxxxx",
                      "name": "root",
                      "showName": "超级管理员",
                      "email": "root@idcos.com",
                      "stat": "enable",
                      "role":{},
                      "dept":{},
                      "groups":[]
                    }
                  ]
                }
              }
