#%RAML 1.0
title: 主机节点管理
baseUri: /api/cli/{version}
version: v1
mediaType: application/json


types:
  Node4Add:
    description: 新增主机节点模型定义
    type: object
    properties:
      name:
        description: 主机节点名
        type: string
        required: true
      showName:
        description: 用于显示的主机节点名
        type: string
        required: false
      execUsers:
        description: 主机执行帐号列表
        type: string[]
        required: false
      stat:
        description: 主机状态
        type: string
        required: false
        enum: [online, offline]
        default: online





/node/view:
  post:
    description: 根据条件查询当前调用者权限范围内的主机节点列表
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      ids:
        description: 主机节点ID列表
        required: true
        type: string[]
      name:
        description: 主机节点名
        required: false
        type: string
      showName:
        description: 用于显示的主机节点名
        required: false
        type: string
      stat:
        description: 主机状态
        required: false
        type: string
        enum: [online, offline]
      pageNo:
        description: 分页起始页码
        required: false
        default: 1
      pageSize:
        description: 单个分页记录数
        required: false
        default: 10

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "pageNo": 1,
                  "pageSize": 10,
                  "totalRows": 1000,
                  "totalPages": 100,
                  "rows":
                  [
                    {
                      "id": "xxxxxx",
                      "name": "root",
                      "showName": "超级管理员",
                      "ConfLastChanged": "2015-11-11 01:01:01",
                      "confLastApplied": "2015-11-11 01:30:01",
                      "execUsers": ["root","idcos"],
                      "stat": "online"
                    }
                  ]
                }
              }






/node/view/{nodeID}:
  post:
    description: 查询当前调用者权限范围内的指定部署单元信息
    headers:
      Authorization:
        required: true
        type: string

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "id": "xxxxxx",
                  "name": "root",
                  "showName": "超级管理员",
                  "ConfLastChanged": "2015-11-11 01:01:01",
                  "confLastApplied": "2015-11-11 01:30:01",
                  "execUsers": ["root","idcos"],
                  "stat": "online"
                }
              }


/node/add:
  post:
    description: 批量新增主机节点
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      nodes:
        description: 主机节点列表
        type: Node4Add[]
        required: true


    responses:
      200:
       body:
         application/json:
           example: |
            {
              "status": "success",
              "message": "成功"
            }



/node/del:
  post:
    description: 批量删除主机节点
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      unitIDs:
        description: 主机ID列表
        required: true
        type: string[]


    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功",
                "content":
                {
                  "removed": 3
                }
              }


/node/mod:
  post:
    description: 修改主机节点
    headers:
      Authorization:
        required: true
        type: string

    queryParameters:
      id:
        description: 主机节点ID
        required: true
        type: string
      name:
        description: 主机节点名
        required: false
        type: string
      showName:
        description: 用于显示的主机节点名
        required: false
        type: string
      confLastChanged:
        description: 最近一次配置修改时间
        required: false
        type: date
      confLastApplied:
        description: 最近一次配置实施时间
        required: false
        type: date
      execUsers:
        description: 主机执行帐号列表
        required: false
        type: string[]
      stat:
        description: 主机状态
        required: false
        type: string
        enum: [online, offline]


    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "success",
                "message": "成功"
              }