#%RAML 1.0
title: 角色信息管理
baseUri: /api/cli/{version}
version: v1
mediaType: application/json

types:
  Role:
    description:
    type: object
    properties:
      id:
        description: 角色ID
        type: string
      name:
        description: 角色名称
        type: string
      showName:
        description: 用于显示的角色名
        type: string


/role/add:
  post:
    description: 批量新增角色
    headers:
      Authorization:
        required: true
        type: string



/role/del:
  post:
    description: 批量删除角色
    headers:
      Authorization:
        required: true
        type: string


/role/mod:
  post:
    description: 修改角色
    headers:
      Authorization:
        required: true
        type: string


/role/view/{roleID}:
  post:
    description: 根据角色ID查询角色信息
    headers:
      Authorization:
        required: true
        type: string


/role/view:
  post:
    description: 根据条件查询角色列表
    headers:
      Authorization:
        required: true
        type: string
