#%RAML 1.0
title: 用户类API
baseUri: /api/cli/{version}
version: v1
mediaType: application/json

/login:
  post:
    description: 登录信息
    queryParameters:
      userName:
        description: 用户名
        type: string
        required: true
      password:
        description: 密码
        type: string
        required: true
        repeat: true
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "",
                "message": "",
                "content": {
                  "accessToken": ""
                }
              }

/profile/view:
  post:
    description: 个性化配置信息
    headers:
      access-token:
        description: token信息
        type: string
        required: true
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "",
                "message": "",
                "content": {
                  "cmdHistoryLength": "",
                  "less": "less开关",
                  "cmdTimeout": "命令超时时间"
                }
              }

/config/view:
  post:
    description: 共通配置信息
    headers:
      access-token:
        description: token信息
        type: string
        required: true

    responses:
      200:
        body:
          application/json:
            example: |
              {
                "status": "",
                "message": "",
                "content": {
                  "cmdForbidChar": "禁止使用的字符",
                  "cmdState": "黑白名单状态"
                }
              }
